# This workflow integrates ShiftLeft NG SAST with GitHub's code scanning feature
name: NG SAST Code Scanning Demo

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on: push

jobs:
  Scan-Build:
    # Scan runs on ubuntu, mac and windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Perform NG SAST Analysis
      run: |
        docker run -e WORKSPACE -e GITHUB_TOKEN -e SCAN_AUTO_BUILD -v /github/workspace:/app shiftleft/scan-java scan --src /app --type java
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
        SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports
