# This workflow integrates ShiftLeft NG SAST with GitHub's code scanning feature
name: NG SAST Code Scanning Demo

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on: push

jobs:
  Scan-Build:
    # Scan runs on ubuntu, mac and windows
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Maven compile and package
      run: mvn compile package   
    - name: Perform NG SAST Analysis
      run: |
        docker run -e WORKSPACE -e GITHUB_TOKEN \
          -e SCAN_DEBUG_MODE=debug \
          -e SHIFTLEFT_ORG_ID -e SHIFTLEFT_ACCESS_TOKEN -e SHIFTLEFT_API_TOKEN \
          -v ${GITHUB_WORKSPACE}:/app shiftleft/scan-java scan --src /app --type java
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SHIFTLEFT_ORG_ID: ${{ secrets.SHIFTLEFT_ORG_ID }}
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        SHIFTLEFT_API_TOKEN: ${{ secrets.SHIFTLEFT_API_TOKEN }}
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports
